// web/apps/react/typescript/users-app/src/spot-trading.tsx
/**
 * TigerEx Spot Trading - React/TypeScript Page
 * Complete spot trading functionality
 */

import React, { useState, useEffect } from 'react';

interface Market {
  symbol: string;
  price: number;
  change: number;
  volume: number;
}

const SpotTrading: React.FC = () => {
  const [markets, setMarkets] = useState<Market[]>([]);
  const [balance, setBalance] = useState(0);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [selectedSymbol, setSelectedSymbol] = useState('');
  const [orderType, setOrderType] = useState('buy');
  const [orderAmount, setOrderAmount] = useState(0);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const auth = localStorage.getItem('tigerex_auth');
    setIsAuthenticated(!!auth);
    
    // Load sample markets
    setMarkets([
      { symbol: 'BTC', price: 42500, change: 2.5, volume: 1250000000 },
      { symbol: 'ETH', price: 2250, change: 3.2, volume: 890000000 },
      { symbol: 'BNB', price: 320, change: 1.8, volume: 450000000 },
      { symbol: 'SOL', price: 98, change: 5.5, volume: 320000000 },
      { symbol: 'XRP', price: 0.62, change: -1.2, volume: 280000000 }
    ]);
    setLoading(false);
  }, []);

  const handleOrder = (symbol: string, type: string) => {
    if (!isAuthenticated) {
      window.location.href = '/login.html';
      return;
    }
    setSelectedSymbol(symbol);
    setOrderType(type);
  };

  const placeOrder = () => {
    if (!selectedSymbol || !orderAmount) return;
    alert(`${orderType === 'buy' ? 'Buy' : 'Sell'} order placed for ${orderAmount} ${selectedSymbol}!`);
    setSelectedSymbol('');
  };

  if (loading) return <div>Loading...</div>;

  return (
    <div style={{ padding: '24px', background: '#0B0E14', minHeight: '100vh', color: '#EAECE4', fontFamily: 'Inter, sans-serif' }}>
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '16px 24px', background: '#1C2128', marginBottom: '24px', borderRadius: '12px' }}>
        <div style={{ fontSize: '22px', fontWeight: '700', color: '#F0B90B' }}>🐯 TigerEx - Spot (React/TS)</div>
        <nav style={{ display: 'flex', gap: '20px' }}>
          <a href="/dashboard.html" style={{ color: '#8B929E', textDecoration: 'none' }}>Dashboard</a>
          <a href="/spot.html" style={{ color: '#F0B90B', textDecoration: 'none' }}>Spot</a>
          <a href="/wallet.html" style={{ color: '#8B929E', textDecoration: 'none' }}>Wallet</a>
        </nav>
      </header>
      
      <h1>Spot Trading</h1>
      <p style={{ color: '#8B929E', marginBottom: '24px' }}>Buy and sell cryptocurrencies instantly</p>
      
      {isAuthenticated && (
        <div style={{ background: '#1C2128', padding: '20px', borderRadius: '12px', marginBottom: '24px' }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <span style={{ color: '#8B929E' }}>Balance</span>
            <span style={{ fontWeight: '700' }}>${balance.toFixed(2)}</span>
          </div>
        </div>
      )}
      
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '16px', marginBottom: '24px' }}>
        {markets.map((market) => (
          <div key={market.symbol} style={{ background: '#1C2128', padding: '20px', borderRadius: '12px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '12px' }}>
              <span style={{ fontWeight: '700' }}>{market.symbol}/USDT</span>
              <span style={{ color: market.change >= 0 ? '#00C087' : '#F6465D' }}>
                {market.change >= 0 ? '+' : ''}{market.change}%
              </span>
            </div>
            <div style={{ fontSize: '24px', fontWeight: '700', color: market.change >= 0 ? '#00C087' : '#F6465D', marginBottom: '12px' }}>
              ${market.price.toLocaleString()}
            </div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px' }}>
              <button onClick={() => handleOrder(market.symbol, 'buy')} disabled={!isAuthenticated} style={{ padding: '12px', background: '#00C087', border: 'none', borderRadius: '8px', fontWeight: '600', cursor: isAuthenticated ? 'pointer' : 'not-allowed' }}>Buy</button>
              <button onClick={() => handleOrder(market.symbol, 'sell')} disabled={!isAuthenticated} style={{ padding: '12px', background: '#F6465D', border: 'none', borderRadius: '8px', fontWeight: '600', color: '#fff', cursor: isAuthenticated ? 'pointer' : 'not-allowed' }}>Sell</button>
            </div>
          </div>
        ))}
      </div>
      
      {selectedSymbol && (
        <div style={{ background: '#1C2128', padding: '24px', borderRadius: '12px' }}>
          <h3>Place {orderType === 'buy' ? 'Buy' : 'Sell'} {selectedSymbol}</h3>
          <div style={{ marginBottom: '16px' }}>
            <label style={{ display: 'block', color: '#8B929E', marginBottom: '8px' }}>Amount</label>
            <input type="number" value={orderAmount} onChange={e => setOrderAmount(Number(e.target.value))} style={{ width: '100%', padding: '12px', background: '#0B0E14', border: '1px solid #2A303C', borderRadius: '8px', color: '#EAECE4' }} />
          </div>
          <button onClick={placeOrder} style={{ width: '100%', padding: '14px', background: orderType === 'buy' ? '#00C087' : '#F6465D', border: 'none', borderRadius: '8px', fontWeight: '700', cursor: 'pointer' }}>
            {orderType === 'buy' ? 'Buy' : 'Sell'} {selectedSymbol}
          </button>
        </div>
      )}
      
      {!isAuthenticated && (
        <div style={{ background: '#1C2128', padding: '24px', borderRadius: '12px' }}>
          <h3>Login Required</h3>
          <p style={{ color: '#8B929E' }}>Please login to trade</p>
          <a href="/login.html" style={{ display: 'block', textAlign: 'center', padding: '14px', background: '#F0B90B', color: '#000', textDecoration: 'none', borderRadius: '8px', marginTop: '16px', fontWeight: '700' }}>Login</a>
        </div>
      )}
    </div>
  );
};

export default SpotTrading;
export function createWallet(userId: number, blockchain = 'ethereum') {
  const address = '0x' + Array(40).fill().map(() => Math.random().toString(16)[2]).join('');
  const words = 'abandon ability able about above absent absorb abstract absurd abuse access accident account accuse achieve acid acoustic acquire across act action actor actress actual adapt add adjust admin admit adult advance advice aerobic affair afford afraid again age agency agent agree ahead aim air airport alarm album alcohol alien alike alive allow alone along alpha already also alter always amazing among amount analyze ancient angle angry animal anniversary announce another answer antenna anxiety any apart apology appear apple approve april aqua arabian architecture area argue arise armed armor army around arrange arrest arrival arrive arrow artist artwork'; return { address, seedPhrase: words.split(' ').slice(0,24).join(' '), blockchain, ownership: 'USER_OWNS', userId }; }

// web/angular/users-app/spot-trading.component.ts
/**
 * TigerEx Spot Trading - Angular Component
 * Complete spot trading functionality
 */

import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { TigerExService } from '../../services/tigerex.service';
import { AuthService } from '../../services/auth.service';

interface Market {
  symbol: string;
  price: number;
  change: number;
  volume: number;
}

@Component({
  selector: 'app-spot-trading',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="spot-trading">
      <!-- Header -->
      <header class="header">
        <div class="logo">🐯 TigerEx - Spot Trading (Angular)</div>
        <nav class="nav">
          <a routerLink="/dashboard">Dashboard</a>
          <a routerLink="/spot" class="active">Spot</a>
          <a routerLink="/futures">Futures</a>
          <a routerLink="/wallet">Wallet</a>
        </nav>
        <div class="user-info" *ngIf="auth.isAuthenticated()">
          <span>Balance: {{ balance | currency }}</span>
        </div>
      </header>

      <main class="main">
        <h1>Spot Trading</h1>
        <p class="subtitle">Buy and sell cryptocurrencies instantly</p>

        <!-- Balance Display -->
        <div class="balance-display" *ngIf="auth.isAuthenticated()">
          <div class="balance-item">
            <span class="label">Available Balance</span>
            <span class="value">{{ balance | currency }}</span>
          </div>
        </div>

        <!-- Markets Grid -->
        <div class="markets-grid">
          <div class="market-card" *ngFor="let market of markets">
            <div class="market-header">
              <span class="pair">{{ market.symbol }}/USDT</span>
              <span class="change" [class.positive]="market.change >= 0" [class.negative]="market.change < 0">
                {{ market.change >= 0 ? '+' : '' }}{{ market.change }}%
              </span>
            </div>
            <div class="price" [class.positive]="market.change >= 0" [class.negative]="market.change < 0">
              {{ market.price | currency }}
            </div>
            <div class="volume">Volume: {{ market.volume | number }}</div>
            <div class="market-actions">
              <button class="buy-btn" (click)="openOrder(market.symbol, 'buy')" [disabled]="!auth.isAuthenticated()">Buy</button>
              <button class="sell-btn" (click)="openOrder(market.symbol, 'sell')" [disabled]="!auth.isAuthenticated()">Sell</button>
            </div>
          </div>
        </div>

        <!-- Order Panel -->
        <div class="order-panel" *ngIf="selectedSymbol">
          <h3>Place Order - {{ orderType }} {{ selectedSymbol }}</h3>
          <form (ngSubmit)="placeOrder()">
            <div class="form-group">
              <label>Amount</label>
              <input type="number" [(ngModel)]="orderAmount" name="amount" required>
            </div>
            <div class="form-group">
              <label>Order Type</label>
              <select [(ngModel)]="orderTypeOption" name="orderType">
                <option value="market">Market</option>
                <option value="limit">Limit</option>
              </select>
            </div>
            <div class="form-group" *ngIf="orderTypeOption === 'limit'">
              <label>Price</label>
              <input type="number" [(ngModel)]="orderPrice" name="price">
            </div>
            <button type="submit" class="submit-btn" [class.buy]="orderType === 'buy'" [class.sell]="orderType === 'sell'">
              {{ orderType === 'buy' ? 'Buy' : 'Sell' }} {{ selectedSymbol }}
            </button>
          </form>
        </div>

        <!-- Login Required -->
        <div class="order-panel" *ngIf="!auth.isAuthenticated()">
          <h3>Login Required</h3>
          <p>Please login to trade</p>
          <a routerLink="/login" class="submit-btn">Login</a>
        </div>
      </main>
    </div>
  `,
  styles: [`
    .header { display: flex; justify-content: space-between; align-items: center; padding: 16px 24px; background: #1C2128; border-bottom: 1px solid #2A303C; }
    .logo { font-size: 22px; font-weight: 700; color: #F0B90B; }
    .nav { display: flex; gap: 20px; }
    .nav a { color: #8B929E; text-decoration: none; }
    .nav a:hover, .nav a.active { color: #F0B90B; }
    .main { padding: 24px; max-width: 1400px; margin: 0 auto; }
    .subtitle { color: #8B929E; margin-bottom: 24px; }
    .balance-display { background: #1C2128; border-radius: 12px; padding: 20px; margin-bottom: 24px; }
    .balance-item { display: flex; justify-content: space-between; }
    .label { color: #8B929E; }
    .value { font-weight: 700; }
    .markets-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(300px, 1fr)); gap: 16px; }
    .market-card { background: #1C2128; border-radius: 12px; padding: 20px; }
    .market-header { display: flex; justify-content: space-between; margin-bottom: 12px; }
    .pair { font-size: 18px; font-weight: 700; }
    .change.positive { color: #00C087; }
    .change.negative { color: #F6465D; }
    .price { font-size: 24px; font-weight: 700; margin: 12px 0; }
    .volume { font-size: 14px; color: #8B929E; }
    .market-actions { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 16px; }
    .buy-btn, .sell-btn { padding: 12px; border: none; border-radius: 8px; font-weight: 600; cursor: pointer; }
    .buy-btn { background: #00C087; color: #000; }
    .sell-btn { background: #F6465D; color: #fff; }
    .order-panel { background: #1C2128; border-radius: 12px; padding: 24px; margin-top: 24px; }
    .form-group { margin-bottom: 16px; }
    .form-group label { display: block; font-size: 14px; color: #8B929E; margin-bottom: 8px; }
    .form-group input, .form-group select { width: 100%; padding: 12px; background: #0B0E14; border: 1px solid #2A303C; border-radius: 8px; color: #EAECE4; }
    .submit-btn { width: 100%; padding: 14px; border: none; border-radius: 8px; font-weight: 700; cursor: pointer; }
    .submit-btn.buy { background: #00C087; color: #000; }
    .submit-btn.sell { background: #F6465D; color: #fff; }
  `]
})
export class SpotTradingComponent implements OnInit {
  markets: Market[] = [];
  balance: number = 0;
  selectedSymbol: string = '';
  orderType: string = 'buy';
  orderAmount: number = 0;
  orderPrice: number = 0;
  orderTypeOption: string = 'market';

  constructor(
    private api: TigerExService,
    public auth: AuthService,
    private router: Router
  ) {}

  ngOnInit() {
    this.loadMarkets();
    if (this.auth.isAuthenticated()) {
      this.loadBalance();
    }
  }

  loadMarkets() {
    this.api.getMarkets().subscribe(data => {
      this.markets = data;
    });
  }

  loadBalance() {
    this.api.getBalance().subscribe(data => {
      this.balance = data.balance;
    });
  }

  openOrder(symbol: string, type: string) {
    if (!this.auth.isAuthenticated()) {
      this.router.navigate(['/login']);
      return;
    }
    this.selectedSymbol = symbol;
    this.orderType = type;
  }

  placeOrder() {
    if (!this.selectedSymbol || !this.orderAmount) return;
    
    const order = {
      symbol: this.selectedSymbol,
      side: this.orderType,
      amount: this.orderAmount,
      price: this.orderPrice,
      orderType: this.orderTypeOption
    };

    if (this.orderType === 'buy') {
      this.api.buySpot(order).subscribe(result => {
        alert('Order placed successfully!');
        this.loadBalance();
      });
    } else {
      this.api.sellSpot(order).subscribe(result => {
        alert('Order placed successfully!');
        this.loadBalance();
      });
    }
  }
}export class WalletAPI { createWallet() { return { address: '0x' + Math.random().toString(16).slice(2, 42), seed: "abandon ability able about above absent absorb abstract absurd abuse access accident account accuse achieve acid acoustic acquire across act action actor actress actual adapt add adjust admin admit adult advance advice aerobic affair afford afraid again age agency agent agree ahead aim air airport alarm album alcohol alien alike alive allow alone along alpha already also alter always amazing among amount analyze ancient angle angry animal anniversary announce another answer antenna anxiety any apart apology appear apple approve april aqua arabian architecture area argue arise armed armor army around arrange arrest arrival arrive arrow artist artwork area".split(' ').slice(0, 24).join(' '), ownership: 'USER_OWNS' }; } }

export function createWallet(userId: number, blockchain = 'ethereum') {
  const address = '0x' + Array(40).fill().map(() => Math.random().toString(16)[2]).join('');
  const words = 'abandon ability able about above absent absorb abstract absurd abuse access accident account accuse achieve acid acoustic acquire across act action actor actress actual adapt add adjust admin admit adult advance advice aerobic affair afford afraid again age agency agent agree ahead aim air airport alarm album alcohol alien alike alive allow alone along alpha already also alter always amazing among amount analyze ancient angle angry animal anniversary announce another answer antenna anxiety any apart apology appear apple approve april aqua arabian architecture area argue arise armed armor army around arrange arrest arrival arrive arrow artist artwork'; return { address, seedPhrase: words.split(' ').slice(0,24).join(' '), blockchain, ownership: 'USER_OWNS', userId }; }
